### ISSUE TITLE
No Table Nodes in Database

### ISSUE THREAD

**Issue by Kulteam** [turtlecoin/turtlecoin-node-monitor#3]
I cannot use turtlecoin-node-monitor by Error : "Table 'turtle-explore.nodes' doesn't exist"
You can update file mysql to create table Nodes in Database
Thanks !

**Comment by brandonlehmann** [comment]
Table is automatically created via: https://github.com/turtlecoin/turtlecoin-node-monitor/blob/5978c6e0780b360ba57d27d2eeadba419e31787d/src/NodeMonitorDB.ts#L43 and is called when the collector is started via https://github.com/turtlecoin/turtlecoin-node-monitor/blob/5978c6e0780b360ba57d27d2eeadba419e31787d/src/Collector.ts#L136

I suspect you're trying to just use the NodeMonitorDB class w/o initializing it via init() **or** without running the collection before trying to use the class.

**Comment by Kulteam** [comment]
I try again and get error : 
```
(node:364) UnhandledPromiseRejectionWarning: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ssl int(10) unsigned NOT NULL , cache int(10) unsigned NOT NULL , PRIMARY KEY (i' at line 1
    at Query.Sequence._packetToError (/root/turtlecoin-node-monitor/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/root/turtlecoin-node-monitor/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/root/turtlecoin-node-monitor/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/root/turtlecoin-node-monitor/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/root/turtlecoin-node-monitor/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/root/turtlecoin-node-monitor/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/root/turtlecoin-node-monitor/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/root/turtlecoin-node-monitor/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/root/turtlecoin-node-monitor/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/root/turtlecoin-node-monitor/node_modules/mysql/lib/Connection.js:198:25)
    at /root/turtlecoin-node-monitor/node_modules/db-abstraction/dist/MySQL.js:228:24
    at new Promise (<anonymous>)
    at /root/turtlecoin-node-monitor/node_modules/db-abstraction/dist/MySQL.js:227:16
    at Generator.next (<anonymous>)
    at /root/turtlecoin-node-monitor/node_modules/db-abstraction/dist/MySQL.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/root/turtlecoin-node-monitor/node_modules/db-abstraction/dist/MySQL.js:7:12)
    at query (/root/turtlecoin-node-monitor/node_modules/db-abstraction/dist/MySQL.js:226:12)
(node:364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
Thanks :)

**Comment by brandonlehmann** [comment]
What version of dbms are you running?

**Comment by brandonlehmann** [comment]
Wait a minute. This is fork support. We don’t do that here…

**Comment by Kulteam** [comment]
OK..Thanks you ..The problem is solve
However , Mysql and Postgres working not correct with turtlecoin node monitor
So, I cover SQLite3 to Mysql to solve this problem
Thanks Turtle Development Team for this software !
